name: find_your_mind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  drift: ^2.23.0
  drift_sqflite: ^2.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: 6.0.0
  flutter_lints: 6.0.0
  flutter_slidable: 4.0.3
  flutter_svg: 2.2.1
  fluttertoast: 9.0.0
  internet_connection_checker: ^3.0.1
  lucide_icons: 0.257.0
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: 6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.24
  supabase_flutter: 2.10.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.23.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - .env
    
  fonts:
        - family: Nunito
          fonts:
            - asset: assets\fonts\nunito\Nunito-ExtraLight.ttf
              weight: 200
            - asset: assets/fonts/nunito/Nunito-Light.ttf
              weight: 300
            - asset: assets/fonts/nunito/Nunito-Regular.ttf
              weight: 400
            - asset: assets/fonts/nunito/Nunito-Medium.ttf
              weight: 500
            - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
              weight: 600
            - asset: assets/fonts/nunito/Nunito-Bold.ttf
              weight: 700
            - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
              weight: 800
            - asset: assets/fonts/nunito/Nunito-Black.ttf
              weight: 900
